version: "3.8"

services:
  wiki:
    container_name: gml-wiki
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    restart: unless-stopped
    networks:
      - gml-network

networks:
  gml-network:
    external: true
